In [1]:
import numpy as np
import pandas as pd

In [2]:
date  = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### Date and time is by default string when importing from pandas dataframe , first we need to covert datatype into date and time

# Working with Dates

In [6]:
# converting to Datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1.Exact year

In [8]:
date['date_year'] = date['date'].dt.year
date['date_month'] = date['date'].dt.month
date['date_month_name'] = date['date'].dt.month_name()
date['date_day'] = date['date'].dt.day

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
162,2019-11-17,1775,25,4,2019,11,November,17
707,2019-07-06,2247,16,9,2019,7,July,6
778,2018-12-13,2235,16,14,2018,12,December,13
568,2019-12-01,4505,25,1,2019,12,December,1
754,2019-05-03,2323,25,122,2019,5,May,3

In [9]:
#  day of week
date['date_dow'] = date['date'].dt.dayofweek

date['day_name'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [10]:
# is weekend ??

date['date_is_weekend'] = np.where(date['day_name'].isin(['Sunday', 'Saturday']),1,0)

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,day_name,date_is_weekend
517,2019-01-06,6671,20,28,2019,1,January,6,6,Sunday,1
472,2019-11-05,7464,0,3,2019,11,November,5,1,Tuesday,0
316,2019-01-24,4173,23,2,2019,1,January,24,3,Thursday,0
686,2018-12-29,1715,16,1,2018,12,December,29,5,Saturday,1
181,2019-04-12,1744,13,2,2019,4,April,12,4,Friday,0

## Extract Quarter

In [11]:
date['date_quarter'] = date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,day_name,date_is_weekend,date_quarter
567,2019-11-15,2457,3,24,2019,11,November,15,4,Friday,0,4
652,2019-10-29,2306,14,9,2019,10,October,29,1,Tuesday,0,4
562,2018-12-01,348,25,4,2018,12,December,1,5,Saturday,1,4
185,2019-11-29,4294,14,4,2019,11,November,29,4,Friday,0,4
806,2019-07-13,3576,25,85,2019,7,July,13,5,Saturday,1,3

## Extract Time elapsed between dates

In [12]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 7, 12, 58, 53, 733769)

In [13]:
today-date['date']

0     2401 days 12:58:53.733769
1     2883 days 12:58:53.733769
2     2814 days 12:58:53.733769
3     2516 days 12:58:53.733769
4     2739 days 12:58:53.733769
                 ...
995   2829 days 12:58:53.733769
996   2770 days 12:58:53.733769
997   2618 days 12:58:53.733769
998   2683 days 12:58:53.733769
999   2457 days 12:58:53.733769
Name: date, Length: 1000, dtype: timedelta64[ns]

In [14]:
(today-date['date']).dt.days

0      2401
1      2883
2      2814
3      2516
4      2739
       ...
995    2829
996    2770
997    2618
998    2683
999    2457
Name: date, Length: 1000, dtype: int64

## Working with Time

In [15]:
# Time is object first we need to convert to datetime
time['date']  = pd.to_datetime(time['date'])

In [18]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

# Exact time part

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,minute,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time Difference

In [19]:
today - time['date']

0     4587 days 12:08:53.733769
1     4451 days 13:18:53.733769
2     4937 days 12:37:53.733769
3     4239 days 12:27:53.733769
4     4636 days 13:47:53.733769
                 ...
995   5226 days 12:08:53.733769
996   4547 days 13:44:53.733769
997   5012 days 13:21:53.733769
998   5128 days 13:24:53.733769
999   4400 days 13:33:53.733769
Name: date, Length: 1000, dtype: timedelta64[ns]

In [21]:
# in seconds
(today - time['date'])/np.timedelta64(1,'s')

# in minutes
(today - time['date'])/np.timedelta64(1,'m')

# in hours
(today - time['date'])/np.timedelta64(1,'h')

0      110100.148259
1      106837.314926
2      118500.631593
3      101748.464926
4      111277.798259
           ...
995    125436.148259
996    109141.748259
997    120301.364926
998    123085.414926
999    105613.564926
Name: date, Length: 1000, dtype: float64